# Generated by Django 5.1.2 on 2024-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('product', models.CharField(max_length=255)),
                ('credit_type', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('rating_int', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('verified_customer', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('helpful', models.IntegerField()),
                ('not_helpful', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('sentiment_category', models.CharField(max_length=100)),
                ('dominant_topic', models.CharField(max_length=100)),
                ('topic1', models.CharField(blank=True, max_length=100, null=True)),
                ('topic2', models.CharField(blank=True, max_length=100, null=True)),
                ('topic3', models.CharField(blank=True, max_length=100, null=True)),
                ('topic4', models.CharField(blank=True, max_length=100, null=True)),
                ('topic5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
